### PR TITLE
Update README with Build Troublesheeting re. "Could not get unknown p…

### PR DESCRIPTION
**Pull request by vorburger**
…roperty"

### CODE REVIEW

**Comment by connorhartley** [comment]
This isn't necessary in my opinion, as the README clearly explains how you should clone the project correctly. https://github.com/LanternPowered/LanternServer#clone "The following steps will ensure your project is **cloned properly**."

**Comment by Cybermaxke** [comment]
I have to agree with @connorhartly, the readme clearly explains what to do. If you get the build error, you probably didn't read the readme anyway. If anything, I would provide a more explaining exception message when running gradle.

**Comment by Cybermaxke** [comment]
I added a meaningful error message in the following commit:
https://github.com/LanternPowered/LanternServer/commit/61b3d181e87d571bcea01fbab8093a0a718578f8
https://github.com/LanternPowered/LanternServer/blob/master/gradle/lantern.gradle#L20

**Comment by vorburger** [comment]
Thanks a lot @Cybermaxke !

**Pull request closed without merging**
