### PR TITLE
Basic crafting/smelting and furnace support

### PR DESCRIPTION
**Pull request by Cybermaxke**
Features:
- Implemented crafting and smelting recipes
- Implemented crafting table - Opens now inventory when right clicking and can craft recipes
- Implemented furnace - Can be openened, smelt items
- Implemented all the exposed recipe API interfaces
- Crafting recipes:
  - Added shaped and shapeless crafting recipes
  - Added a simplified interface for implementing custom recipes
  - Works in player inventory and crafting table
  - Shift clicking craft behavior
  - Allow multiple input items for a single slot, although it's very unlikely to be used unless 9 items aren't enough
  - Allow remaining items to be applied to the `Ingredient` (`IIngredient`).
- Smelting recipes:
  - Use multiple input items in the input slot to get a different result, for example `2x iron_ingot -> steel_ingot`
  - Allow the smelt time of a recipe to be specified
  - Register custom fuel items with a variable burn time
- Probably a lot more...

Not included (due the size of the PR):
- Proper shift clicking in the furnace: The handling of shift clicking should be partially redone and splitting it in two layers, force overriding/tracking client changes and shift clicking on the server side. The server side shift clicking behavior should not be limited by client updates/glitches, so we track them and fix it.
- Crafting book + prepare grid behavior: Requires vanilla recipes
- Vanilla recipes: Will be included in a json loading system for recipes, nothing will be hardcoded in the end except maybe special cases like fireworks

### CODE REVIEW

**Comment by Cybermaxke** [comment]
@Meronat You can checkout the available recipes in the registry modules:
- https://github.com/LanternPowered/LanternServer/blob/recipes-rebase/src/main/java/org/lanternpowered/server/item/recipe/crafting/LanternCraftingRecipeRegistryModule.java
- https://github.com/LanternPowered/LanternServer/blob/recipes-rebase/src/main/java/org/lanternpowered/server/item/recipe/smelting/LanternSmeltingRecipeRegistryModule.java
- https://github.com/LanternPowered/LanternServer/blob/recipes-rebase/src/main/java/org/lanternpowered/server/item/recipe/fuel/LanternFuelRegistryModule.java

**Comment by Meronat** [comment]
@Cybermaxke As I am looking through this right now and testing it out, I noticed shift clicking a stack of fuel(in this case coal) into the furnace places the stack into both input slots of the furnace client side. The actual stack ends up in the top slot while the ghost item stack is in the bottom slot and disappears once you move it.

There is also weird behavior if both slots have the fuel in it, but it's hard to explain.

Part of the problem possibly can be solved by prioritizing the bottom slot if it is fuel, but some of the issues will still remain.

**Comment by Meronat** [comment]
@Cybermaxke As I am looking through this right now and testing it out, I noticed shift clicking a stack of fuel(in this case coal) into the furnace places the stack into both input slots of the furnace client side. The actual stack ends up in the top slot while the ghost item stack is in the bottom slot and disappears once you move it.

There is also weird behavior if both slots have the fuel in it, but it's hard to explain.

Part of the problem possibly can be solved by prioritizing the bottom slot if it is fuel, but some of the issues will still remain.

**Edit:** Oops I see you mentioned this already.

**Comment by Meronat** [comment]
A note for later implementation - Crafting benches don't drop their items yet

**Comment by Cybermaxke** [comment]
@Meronat I might fix the ghost stacks for now in the furnace, but implement the proper behavior later with the refactor. As for the crafting benches drops, I could already implement that in this PR.

**Comment by Cybermaxke** [comment]
@Meronat The test plugin is a good idea, I will try to finish the PR tomorrow and merge it then.

Todo list:

- [ ] Fix furnace shift clicking ghost items
- [ ] Drop crafting table items when closing the inventory
- [ ] Add a test plugin, maybe move the current (test) recipes to that plugin

**Comment by Meronat** [comment]
The changes look good to me and work appropriately :)

**Pull request closed without merging**
