### PR TITLE
General pagination fixes and cleanup - Fixes #29

### LINKED ISSUE #29: Port: Fix pagination styling issue and clean up class a little; Additional pagination fixes.
https://github.com/SpongePowered/SpongeCommon/pull/1332

### PR DESCRIPTION
**Pull request by Meronat**
Some is new and some is from past Sponge commits - Fixes #29

### CODE REVIEW

**Comment by Meronat** [comment]
Still need to fix specific page command and miscount of line amount.

**Comment by Cybermaxke** [comment]
@Meronat Status?

**Comment by Meronat** [comment]
@Cybermaxke I will get back to this soon.

**Comment by Meronat** [comment]
Now that my API PR got in I will finish this when I wake up. I still have to fix one thing relating to counting lines, but I should be able to figure it out.

**Comment by Meronat** [comment]
So this seems to be good in a sense of porting features over, but I posted in the #development channel on Discord about my issues with proper amount of lines. I spent quite a while on it but couldn't figure it out, but other than that this PR supports my latest API changes and ports other various SpongeCommon changes.

**Pull request closed without merging**
