### PR TITLE
Refactor inventory containers. Separate client and server container concept.

### PR DESCRIPTION
**Pull request by Cybermaxke**
This PR refactors the inventory containers, it divides the container in two different layers. A server layer which will handle all our custom/vanilla click movements. And the client layer, which will "guess" what the client will update so we can revert these changes if they don't match our own ones. The client container concept is also being expanded that you can bind any server slot to a specific client slot, the indexes don't have to match (slots can be disabled and also put an icon in it).

This is still WIP, needs cleaning up in some places, some things still need to be moved and everything needs to be properly tested.

Features:
- Refactor the shift clicking handling, the `OpenableInventory` defines now how shift clicking is handled, and not by the slots like it was before. It allows a greater customizability.
- Separate server and client containers for complete client container control.
- Added all the vanilla client container implementations.
- Implemented furnace shift clicking.

### CODE REVIEW

**Comment by Cybermaxke** [comment]
@Meronat Shift clicking in furnaces is now a thing. ;)

**Comment by Meronat** [comment]
This became a pretty big undertaking but from the looks of it will definitely be worthwhile.

**Comment by Cybermaxke** [comment]
@Meronat Could you give this another try? It should be working now.

**Comment by Meronat** [comment]
@Cybermaxke Just saw this now. I'll give it a test :)

**Comment by Meronat** [comment]
It's working now for furnaces it seems, nice job. The only problem I have found(not necessarily related) is that the progress bar for fuel does not retract(goes down/runs out?) as it runs out.

It also seems to work between my hotbar and main inventory, as well as with single chests but not double chests.

With double chests my items disappear then reappear in my inventory when I close the container.

**Comment by Meronat** [comment]
Also I'm not sure if this can be helped, but when I shift click an item to go into the ingredient slot of the furnace, it seems to go to the part of the player inventory it was not in very quickly then go to the ingredient slot.

So hotbar -> main -> ingredient slot or main -> hotbar -> ingredient slot

This does not happen with the fuel

**Comment by Cybermaxke** [comment]
@Meronat What was the ingrediënt in the last issue? It was probably original client behavior.

**Comment by Meronat** [comment]
@Cybermaxke It was a half stack or so of iron ingots for the steel recipe

**Comment by Cybermaxke** [comment]
@Meronat You can retry this PR, I fixed the issues you had. ;)

**Comment by Meronat** [comment]
All of my issues seem to be fixed, nice job. I'll give it a more complete review soon.

**Pull request closed without merging**
