### PR TITLE
Inventory refactor part 2 - inventory and archetype builders

### PR DESCRIPTION
**Pull request by Cybermaxke**
The big inventory refactor is reaching it's end, so testing can get started. Testing should also target possible inventory plugins.

Changes:
- Inventories are no longer populated inside a inventory, but through builders.
- Every inventory (except views) are have also a archetype assigned to them.
- Implemented the SpongeAPI archetype and inventory builders.
- Containers no longer contain the inventory structure, but just slots (ContainerSlots). You can use the transform methods on slots to get the original ones.
- All the inventories that are generated with a carrier will also implement CarriedInventory (through class generation)
- A client container bug fix. Long clicking a slot (without dragging) was also considered a dragging mode and is now handled like a normal click. This was causing items to disappear.

TODO:
- Figure out how to properly handle all the property operations? (When comparing two properties that have the DELEGATE operation, fallback to EQUAL?)
- Testing
- Bugs?
- Anything missing?

### CODE REVIEW

**Comment by Meronat** [comment]
I will give this a full review and test it thoroughly tonight. From a quick glance it looks pretty good though :>

**Comment by Meronat** [comment]
I'm not sure what issues I'm supposed to report relating to functionality for this PR, but I have found a few issues in general with inventories/containers.

Shift clicking iron ore(and others like gold) in the furnace does not bring it to the cooking slot like the client expects, but rather to the opposite part of the inventory(hotbar to main/main to hotbar) or stays in its current spot if the other is full. This does not happen to coal which goes to the proper slot.

I cannot open double chests, but I can open single chests which do work well. 

Inventories do not have the proper names, most just saying `Inventory`. The crafting bench has the proper name.

Furnaces do not work at all anymore, at least with coal and iron ore(I recall this working before).

**Comment by Meronat** [comment]
Actually just noticed there was a stack trace when opening double chests: https://gist.github.com/Meronat/3eb9e2a30a53b41d48bd4c2f70e7b4c7

**Comment by Cybermaxke** [comment]
@Meronat The iron ingot recipe isn't registered yet, but you could combine two iron ingots into a steel ingot. And I will fix the inventory names and the double chest error.

**Comment by Meronat** [comment]
Will do some more testing tomorrow and a code review. Maybe rebase on master?

**Comment by Cybermaxke** [comment]
@Meronat I am going to merge this in a few days. In case you want to do some more testing, I am also going to test a bit more. We can always fix any other issues later as they pop up.

**Pull request merged**
